#ifndef RESOURCE_H
#define RESOURCE_H

#define IDD_ACCOUNT_DIALOG 101
#define IDI_APP_ICON 102
#define IDD_UPDATE_SETTINGS 200

#define IDC_EDIT_USERNAME 1001
#define IDC_EDIT_ALIAS 1002
#define IDC_EDIT_GROUP 1003
#define IDC_EDIT_DESCRIPTION 1004
#define IDC_EDIT_ROBLOSECURITY 1005
#define IDC_CHECK_FAVORITE 1006

#define IDC_RADIO_UPDATE_EVERYDAY 2001
#define IDC_RADIO_UPDATE_WEEKLY 2002
#define IDC_RADIO_UPDATE_MONTHLY 2003
#define IDC_RADIO_UPDATE_NEVER 2004

#endif // RESOURCE_H
